'use client';

import { setManifest } from 'heroshot/next';
// @ts-expect-error - generated by withHeroshot() in next.config.js
import manifest from '@heroshot/manifest';

setManifest(manifest);

export default function Providers({ children }: Readonly<{ children: React.ReactNode }>) {
  return <>{children}</>;
}
