#!/bin/sh

# Block commits with AI tool co-authors or footprints
# Only humans can bear responsibility for code - commits must be under your name

COMMIT_MSG_FILE="$1"

# Check if commit message file exists
if [ ! -f "$COMMIT_MSG_FILE" ]; then
  exit 0
fi

COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check for AI co-author patterns
if echo "$COMMIT_MSG" | grep -qiE "Co-Authored-By:.*(Claude|anthropic\.com|openai\.com|GitHub Copilot|Cursor|Codeium)"; then
  echo ""
  echo "  BLOCKED: AI co-author detected"
  echo ""
  echo "  Only humans can bear responsibility for code."
  echo "  Commits must be authored by you, not an AI assistant."
  echo ""
  echo "  Please remove the Co-Authored-By line and commit under your name."
  echo ""
  exit 1
fi

# Check for AI-generated signatures
if echo "$COMMIT_MSG" | grep -qiE "Generated (with|by).*(Claude|GPT|Copilot|Cursor|AI)"; then
  echo ""
  echo "  BLOCKED: AI-generated signature detected"
  echo ""
  echo "  Only humans can bear responsibility for code."
  echo "  You are the author - own your commits."
  echo ""
  echo "  Please remove the 'Generated by' line from your commit message."
  echo ""
  exit 1
fi

exit 0
